name: Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-workflow-call:
      uses: vutfitdiscord/rubbergod/.github/workflows/lint.yml@main

  Deployment_Production:
    runs-on: ubuntu-latest
    environment: Production
    needs: lint-workflow-call
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Execute deployment on SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          port: 22
          script: |
            echo "================== Pull Changes =================="
            cd Rubbergod
            git pull

            echo "================== Build and Push Image =================="
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker build . --tag ghcr.io/vutfitdiscord/rubbergod:latest
            docker push ghcr.io/vutfitdiscord/rubbergod:latest

            echo "================== Restart Services =================="
            docker compose down && docker compose up --build -d

            echo "================== Clean Up Images =================="
            echo "y" | docker image prune -a
